baseURL = 'https://matthias-vdc.github.io/'
languageCode = 'en-us'
title = 'Matthias Van de Casteele'
theme = ["PaperMod"]
enableGitInfo = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokai'
    tabWidth = 4
    wrapperClass = 'highlight'

[params]
  defaultTheme = "dark"
  disableThemeToggle = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params.assets]
    favicon = "favicon.ico"
    favicon32x32 = "favicon.svg"
    appleTouchIcon = "apple-touch-icon.png"
    favicon96x96 = "favicon-96x96.png"
    webmanifest = "site.webmanifest"

[frontmatter]
  lastmod = "lastmod"
