baseURL = 'https://matthias-vdc.github.io/'
languageCode = 'en-us'
title = 'Matthias Van de Casteele'
theme = ["PaperMod"]
enableGitInfo = true

[outputs]
    home = ["HTML", "RSS"]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'nordic'
    tabWidth = 4
    wrapperClass = 'highlight'

[params]
  defaultTheme = "dark"
  disableThemeToggle = false
  author = "Matthias Van de Casteele"
  description = "Personal blog of Matthias Van de Casteele - Anything about security, web, hardware, technology and anything else that I find interesting"
  images = ["cover.png"]

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [params.profileMode]
    enabled = true
    title = "Matthias Van de Casteele"
    subtitle = "Tech tinkerer"
    imageUrl = "me.jpg"
    imageWidth = 120
    imageHeight = 120
    imageDisplay = "rounded"

    [[params.socialIcons]]
      name = "github"
      url = "https://github.com/matthias-vdc"
    [[params.socialIcons]]
      name = "linkedin"
      url = "https://www.linkedin.com/in/matthiasvdc/"

    [[params.profileMode.buttons]]
      name = "Latest Posts"
      url = "posts"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params.assets]
    favicon = "favicon.ico"
    favicon32x32 = "favicon.svg"
    appleTouchIcon = "apple-touch-icon.png"
    favicon96x96 = "favicon-96x96.png"
    webmanifest = "site.webmanifest"

[frontmatter]
  lastmod = "lastmod"
